apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: cms-cache-svc-secret
objects:
- apiVersion: v1
  stringData:
     cms_cache_svc_mongo_cache_rw_ds_account: ${cms_cache_svc_mongo_cache_rw_ds_account}
     cms_cache_svc_mongo_cache_rw_ds_passcode: ${cms_cache_svc_mongo_cache_rw_ds_passcode}     
  type: Opaque
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app: cms-cache-svc
    name: cms-cache-svc-secret
parameters:
 - name: cms_cache_svc_mongo_cache_rw_ds_account
   description: mongo db cache db username
   required: true
 - name: cms_cache_svc_mongo_cache_rw_ds_passcode
   description: mongo db cache db password
   required: true
 