apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: cicd-demo-app
message: cicd-demo-app
metadata:
  annotations:
    description: cicd-demo-app template
    iconClass: icon-rh-openjdk
    openshift.io/display-name: cicd-demo-app
    openshift.io/provider-display-name: HAITS EAO
    tags: cicd
  name: cicd-demo-app-template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations: {}
    labels:
      app: cicd-demo-app-${version}
      version: ${version}
    name: cicd-demo-app-${version}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: cicd-demo-app-${version}
      version: ${version}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: cicd-demo-app-${version}
          version: ${version}
      spec:
        containers:
          - env:
              - name: bgcolour
                value: ${bgcolour}
            image: '{image:tag}'
            imagePullPolicy: Always
            name: cicd-demo-app-${version}
            ports:
              - containerPort: 8080
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange
parameters:
- description: Background Colour
  displayName: bgcolour
  name: bgcolour
  required: true
- description: Hospital
  displayName: hospital
  name: hospital
  required: true
- description: Version
  displayName: version
  name: version
  required: true
  